# These are supported funding model platforms

github: BitcoinSchema
custom: https://gobitcoinsv.com/#sponsor?utm_source=github&utm_medium=sponsor-link&utm_campaign=go-boost&utm_term=go-boost&utm_content=go-boost